/*
Copyright 2023 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package initialize

// getEmbeddedResourceTypes returns the embedded resource type definitions.
// These are derived from radius-project/resource-types-contrib.
func getEmbeddedResourceTypes() map[string]string {
	return map[string]string{
		"containers.yaml":         containersYAML,
		"persistentVolumes.yaml":  persistentVolumesYAML,
		"routes.yaml":             routesYAML,
		"mySqlDatabases.yaml":     mySqlDatabasesYAML,
		"postgreSqlDatabases.yaml": postgreSqlDatabasesYAML,
		"secrets.yaml":            secretsYAML,
	}
}

// getRecipesContent returns the recipes file content for a platform and tool.
func getRecipesContent(platform, tool string) string {
	return `# Default Recipes for Radius
# Generated by 'rad init'
#
# Each recipe specifies:
#   - resourceType: The Radius resource type (e.g., Applications.Datastores/redisCaches)
#   - recipeKind: Either "terraform" or "bicep"
#   - recipeLocation: Git URL, OCI ref, or file path to the recipe module

# TODO: Add git tags (?ref=v1.0.0)

recipes:
  - resourceType: Radius.Compute/containers
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Compute/containers/recipes/kubernetes/terraform
  
  - resourceType: Radius.Compute/persistentVolumes
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Compute/persistentVolumes/recipes/kubernetes/terraform
  
  - resourceType: Radius.Compute/routes
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git/Compute/routes/recipes/kubernetes/terraform

  - resourceType: Radius.Data/mySqlDatabases
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Data/mySqlDatabases/recipes/kubernetes/terraform

  - resourceType: Radius.Data/postgreSqlDatabases
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Data/postgreSqlDatabases/recipes/kubernetes/terraform
    
  - resourceType: Radius.Security/secrets
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Security/secrets/recipes/kubernetes/terraform
`
}

const containersYAML = `namespace: Radius.Compute
types:
  containers:
    description: |
      The Radius.Compute/containers Resource Type is the primary resource type for running one or more containers. It is always part of a Radius Application. To deploy a Container add a resource to the application definition Bicep file.

      extension radius
      param environment string 

      resource myApplication 'Radius.Core/applications@2025-08-01-preview' = { ... }

      resource myContainer 'Radius.Compute/containers@2025-08-01-preview' = {
        name: 'myContainer'
        properties: {
          environment: environment
          application: myApplication.id
          containers: {
            demo: {
              image: 'ghcr.io/radius-project/samples/demo:latest'
            }
          }
        }
      }

      By default, Containers deploys to Kubernetes. In this case, a Kubernetes Deployment named myContainer is deployed which includes a Pod named myContainer. Your Radius environment may deploy to other container platforms such as Azure Container Instances. 

      To accept network connections, expose a port on the container.

      resource myContainer 'Radius.Compute/containers@2025-08-01-preview' = {
        name: 'myContainer'
        properties: {
          environment: environment
          application: myApplication.id
          containers: {
            demo: {
              image: 'ghcr.io/radius-project/samples/demo:latest'
              ports: {
                web: {
                  containerPort: 3000
                }
              }
            }
          }
        }
      }
      
      When a port is included, a Kubernetes Service named demo with the type ClusterIP is created.

    apiVersions:
      '2025-08-01-preview':
        schema: 
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            containers:
              type: object
              additionalProperties:
                type: object
                properties:
                  image:
                    type: string
                    description: (Required) The container image.
                  ports:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        containerPort:
                          type: integer
                          description: (Required) The network port the container is listening on.
                      required: [containerPort]
                required: [image]
          required: [environment, application, containers]
`

const persistentVolumesYAML = `namespace: Radius.Compute
types:
  persistentVolumes:
    description: |
      The Radius.Compute/persistentVolumes Resource Type creates persistent storage that can be mounted by containers.

    apiVersions:
      '2025-08-01-preview':
        schema:
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            size:
              type: string
              description: (Required) The size of the volume (e.g., "1Gi").
            storageClass:
              type: string
              description: (Optional) The storage class to use.
          required: [environment, application, size]
`

const routesYAML = `namespace: Radius.Compute
types:
  routes:
    description: |
      The Radius.Compute/routes Resource Type defines network routes for responding to external clients.

    apiVersions:
      '2025-08-01-preview':
        schema:
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            kind:
              type: string
              enum: [HTTP, TCP]
              description: (Required) The route kind.
            rules:
              type: array
              items:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        httpPath:
                          type: string
                        port:
                          type: integer
                  backends:
                    type: array
                    items:
                      type: object
                      properties:
                        target:
                          type: string
                        port:
                          type: integer
          required: [environment, application, kind]
`

const mySqlDatabasesYAML = `namespace: Radius.Data
types:
  mySqlDatabases:
    description: |
      The Radius.Data/mySqlDatabases Resource Type provisions MySQL databases.

    apiVersions:
      '2025-08-01-preview':
        schema:
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            database:
              type: string
              description: (Optional) The database name.
          required: [environment, application]
`

const postgreSqlDatabasesYAML = `namespace: Radius.Data
types:
  postgreSqlDatabases:
    description: |
      The Radius.Data/postgreSqlDatabases Resource Type provisions PostgreSQL databases.

    apiVersions:
      '2025-08-01-preview':
        schema:
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            database:
              type: string
              description: (Optional) The database name.
          required: [environment, application]
`

const secretsYAML = `namespace: Radius.Security
types:
  secrets:
    description: |
      The Radius.Security/secrets Resource Type stores sensitive data such as tokens, passwords, keys, and certificates.

    apiVersions:
      '2025-08-01-preview':
        schema:
          type: object
          properties:
            environment:
              type: string
              description: (Required) The Radius Environment ID.
            application:
              type: string
              description: (Required) The Radius Application ID.
            data:
              type: object
              additionalProperties:
                type: object
                properties:
                  value:
                    type: string
                    description: (Required) The secret value.
                  encoding:
                    type: string
                    enum: [raw, base64]
                    description: (Optional) The encoding of the value.
                required: [value]
          required: [environment, application, data]
`
