/*
Copyright 2023 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package github

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// Workflow represents a GitHub Actions workflow.
type Workflow struct {
	Name           string                 `yaml:"name"`
	RunName        string                 `yaml:"run-name,omitempty"`
	On             WorkflowTrigger        `yaml:"on"`
	Permissions    map[string]string      `yaml:"permissions,omitempty"`
	Concurrency    *WorkflowConcurrency   `yaml:"concurrency,omitempty"`
	Env            map[string]string      `yaml:"env,omitempty"`
	Jobs           map[string]WorkflowJob `yaml:"jobs"`
	HeaderComments []string               `yaml:"-"` // Additional header comments (not serialized)
}

// WorkflowTrigger defines what triggers a workflow.
type WorkflowTrigger struct {
	Push             *PushTrigger             `yaml:"push,omitempty"`
	PullRequest      *PullRequestTrigger      `yaml:"pull_request,omitempty"`
	WorkflowDispatch *WorkflowDispatchTrigger `yaml:"workflow_dispatch,omitempty"`
}

// PushTrigger triggers on push events.
type PushTrigger struct {
	Branches []string `yaml:"branches,omitempty"`
	Paths    []string `yaml:"paths,omitempty"`
}

// PullRequestTrigger triggers on pull request events.
type PullRequestTrigger struct {
	Branches []string `yaml:"branches,omitempty"`
	Types    []string `yaml:"types,omitempty"`
}

// WorkflowDispatchTrigger allows manual triggering with inputs.
type WorkflowDispatchTrigger struct {
	Inputs map[string]WorkflowInput `yaml:"inputs,omitempty"`
}

// WorkflowInput defines an input for manual workflow dispatch.
type WorkflowInput struct {
	Description string   `yaml:"description"`
	Required    bool     `yaml:"required"`
	Default     string   `yaml:"default,omitempty"`
	Type        string   `yaml:"type,omitempty"`
	Options     []string `yaml:"options,omitempty"`
}

// WorkflowConcurrency controls concurrent workflow runs.
type WorkflowConcurrency struct {
	Group            string `yaml:"group"`
	CancelInProgress bool   `yaml:"cancel-in-progress,omitempty"`
}

// WorkflowJob represents a job in a workflow.
type WorkflowJob struct {
	Name        string            `yaml:"name,omitempty"`
	RunsOn      string            `yaml:"runs-on"`
	Environment string            `yaml:"environment,omitempty"`
	Permissions map[string]string `yaml:"permissions,omitempty"`
	Needs       []string          `yaml:"needs,omitempty"`
	If          string            `yaml:"if,omitempty"`
	Env         map[string]string `yaml:"env,omitempty"`
	Steps       []WorkflowStep    `yaml:"steps"`
}

// WorkflowStep represents a step in a job.
type WorkflowStep struct {
	Name            string            `yaml:"name,omitempty"`
	ID              string            `yaml:"id,omitempty"`
	Uses            string            `yaml:"uses,omitempty"`
	Run             string            `yaml:"run,omitempty"`
	With            map[string]string `yaml:"with,omitempty"`
	Env             map[string]string `yaml:"env,omitempty"`
	If              string            `yaml:"if,omitempty"`
	ContinueOnError bool              `yaml:"continue-on-error,omitempty"`
	WorkingDir      string            `yaml:"working-directory,omitempty"`
}

// SaveWorkflow writes a workflow to a YAML file.
func SaveWorkflow(filepath string, workflow *Workflow) error {
	data, err := yaml.Marshal(workflow)
	if err != nil {
		return fmt.Errorf("failed to marshal workflow: %w", err)
	}

	// Add header comment
	header := "# Radius deployment workflow\n# Generated by rad init - do not edit manually\n"

	// Add workflow-specific customization comments
	for _, comment := range workflow.HeaderComments {
		header += "#\n# " + comment + "\n"
	}

	header += "\n"
	data = append([]byte(header), data...)

	if err := os.WriteFile(filepath, data, 0644); err != nil {
		return fmt.Errorf("failed to write workflow: %w", err)
	}

	return nil
}

// LoadWorkflow reads a workflow from a YAML file.
func LoadWorkflow(filepath string) (*Workflow, error) {
	data, err := os.ReadFile(filepath)
	if err != nil {
		return nil, fmt.Errorf("failed to read workflow: %w", err)
	}

	var workflow Workflow
	if err := yaml.Unmarshal(data, &workflow); err != nil {
		return nil, fmt.Errorf("failed to parse workflow: %w", err)
	}

	return &workflow, nil
}

// GenerateDeployWorkflow creates the deployment workflow template.
func GenerateDeployWorkflow(provider string) *Workflow {
	workflow := &Workflow{
		Name:    "Radius Deploy",
		RunName: "Radius deploy for ${{ github.event.pull_request.head.ref }}",
		On: WorkflowTrigger{
			PullRequest: &PullRequestTrigger{
				Branches: []string{"main"},
				Types:    []string{"closed"},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "write",
		},
		Concurrency: &WorkflowConcurrency{
			Group:            "radius-deploy-${{ github.event.pull_request.head.ref }}",
			CancelInProgress: false,
		},
		Jobs: map[string]WorkflowJob{
			"deploy": {
				Name:   "Deploy",
				RunsOn: "ubuntu-latest",
				If:     "github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'deploy/')",
				Steps:  generateDeploySteps(provider),
			},
		},
	}

	return workflow
}

// GenerateDestroyWorkflow creates the destruction workflow template.
func GenerateDestroyWorkflow(provider string) *Workflow {
	workflow := &Workflow{
		Name:    "Radius Destroy",
		RunName: "Radius destroy for ${{ github.event.pull_request.head.ref }}",
		On: WorkflowTrigger{
			PullRequest: &PullRequestTrigger{
				Branches: []string{"main"},
				Types:    []string{"closed"},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "write",
		},
		Jobs: map[string]WorkflowJob{
			"destroy": {
				Name:   "Destroy",
				RunsOn: "ubuntu-latest",
				If:     "github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'destroy/')",
				Steps:  generateDestroySteps(provider),
			},
		},
	}

	return workflow
}

// GeneratePlanWorkflow creates the plan workflow template for workflow_dispatch.
func GeneratePlanWorkflow(provider string) *Workflow {
	workflow := &Workflow{
		Name:    "Radius Plan",
		RunName: "Radius plan for ${{ inputs.application }} in ${{ inputs.environment }} environment",
		On: WorkflowTrigger{
			WorkflowDispatch: &WorkflowDispatchTrigger{
				Inputs: map[string]WorkflowInput{
					"environment": {
						Description: "Target environment name",
						Required:    true,
						Type:        "string",
					},
					"application": {
						Description: "Application name to deploy",
						Required:    true,
						Type:        "string",
					},
				},
			},
		},
		Permissions: map[string]string{
			"id-token":      "write",
			"contents":      "write",
			"pull-requests": "write",
		},
		Jobs: map[string]WorkflowJob{
			"plan": {
				Name:   "Generate Plan",
				RunsOn: "ubuntu-latest",
				Steps:  generatePlanSteps(provider),
			},
		},
	}

	return workflow
}

func generateDeploySteps(provider string) []WorkflowStep {
	steps := []WorkflowStep{
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version": "1.23",
				"cache":      "true",
			},
		},
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"path": "app",
			},
		},
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		{
			Name: "Install Radius control plane",
			// Support custom image registry via repository variables (RADIUS_IMAGE_REGISTRY, RADIUS_IMAGE_TAG)
			Run: "cd app && rad install kubernetes --skip-contour-install --set global.repositoryPath=.radius --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// D053: Wait for control plane readiness then create resource group.
		// UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		{
			Name: "Create environment",
			Run:  "rad env create ${{ github.event.inputs.environment || 'default' }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
	}

	// Add cloud-specific authentication
	if provider == "aws" {
		steps = append(steps, WorkflowStep{
			Name: "Configure AWS credentials",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "${{ secrets.AWS_OIDC_ROLE_ARN }}",
				"aws-region":     "${{ secrets.AWS_REGION }}",
			},
		})
	} else if provider == "azure" {
		steps = append(steps, WorkflowStep{
			Name: "Azure Login",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ secrets.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ secrets.AZURE_TENANT_ID }}",
				"subscription-id": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
			},
		})
	}

	// Add deployment step
	steps = append(steps, WorkflowStep{
		Name: "Run deployment",
		Run:  "cd app && rad deploy .radius/model/*.bicep --group github",
		Env: map[string]string{
			"KUBECONFIG": "/tmp/kubeconfig.yaml",
		},
	})

	// Add commit results step
	steps = append(steps, WorkflowStep{
		Name: "Commit deployment results",
		Run: `cd app
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add .radius/deploy/
git commit -m "Record deployment results" --trailer "Radius-Action: deploy" || true
git push origin HEAD:${{ github.ref_name }}`,
	})

	return steps
}

func generateDestroySteps(provider string) []WorkflowStep {
	steps := []WorkflowStep{
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version": "1.23",
				"cache":      "true",
			},
		},
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"path": "app",
			},
		},
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		{
			Name: "Install Radius control plane",
			// Support custom image registry via repository variables (RADIUS_IMAGE_REGISTRY, RADIUS_IMAGE_TAG)
			Run: "cd app && rad install kubernetes --skip-contour-install --set global.repositoryPath=.radius --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// D053: Wait for control plane readiness then create resource group.
		// UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		{
			Name: "Create environment",
			Run:  "rad env create ${{ github.event.inputs.environment || 'default' }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
	}

	// Add cloud-specific authentication (same as deploy)
	if provider == "aws" {
		steps = append(steps, WorkflowStep{
			Name: "Configure AWS credentials",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "${{ secrets.AWS_OIDC_ROLE_ARN }}",
				"aws-region":     "${{ secrets.AWS_REGION }}",
			},
		})
	} else if provider == "azure" {
		steps = append(steps, WorkflowStep{
			Name: "Azure Login",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ secrets.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ secrets.AZURE_TENANT_ID }}",
				"subscription-id": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
			},
		})
	}

	// Add destroy step
	steps = append(steps, WorkflowStep{
		Name: "Run destruction",
		Run:  "cd app && rad destroy .radius/model/*.bicep --group github",
		Env: map[string]string{
			"KUBECONFIG": "/tmp/kubeconfig.yaml",
		},
	})

	// Add commit results step
	steps = append(steps, WorkflowStep{
		Name: "Commit destruction results",
		Run: `cd app
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add .radius/deploy/
git commit -m "Record destruction results" --trailer "Radius-Action: destroy" || true
git push origin HEAD:${{ github.ref_name }}`,
	})

	return steps
}

func generatePlanSteps(provider string) []WorkflowStep {
	steps := []WorkflowStep{
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version": "1.23",
				"cache":      "true",
			},
		},
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"path": "app",
			},
		},
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		{
			Name: "Install Radius control plane",
			// Support custom image registry via repository variables (RADIUS_IMAGE_REGISTRY, RADIUS_IMAGE_TAG)
			Run: "cd app && rad install kubernetes --skip-contour-install --set global.repositoryPath=.radius --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// D053: Wait for control plane readiness then create resource group.
		// UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		{
			Name: "Create environment",
			Run:  "rad env create ${{ github.event.inputs.environment }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
	}

	// Add cloud-specific authentication
	if provider == "aws" {
		steps = append(steps, WorkflowStep{
			Name: "Configure AWS credentials",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "${{ secrets.AWS_OIDC_ROLE_ARN }}",
				"aws-region":     "${{ secrets.AWS_REGION }}",
			},
		})
	} else if provider == "azure" {
		steps = append(steps, WorkflowStep{
			Name: "Azure Login",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ secrets.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ secrets.AZURE_TENANT_ID }}",
				"subscription-id": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
			},
		})
	}

	// Generate plan via Radius control plane API
	// Note: rad deploy --plan generates a plan without executing deployment
	steps = append(steps, WorkflowStep{
		Name: "Generate deployment plan",
		Run:  "cd app && rad deploy .radius/model/${{ github.event.inputs.application }}.bicep --plan --environment ${{ github.event.inputs.environment }} --application \"${{ github.event.inputs.application }}\" --group github --output .radius/plan/",
		Env: map[string]string{
			"KUBECONFIG": "/tmp/kubeconfig.yaml",
		},
	})

	// Create branch and PR
	steps = append(steps, WorkflowStep{
		Name: "Create deployment PR",
		Run: `cd app
BRANCH_NAME="deploy/${{ github.event.inputs.application || 'all' }}/${{ github.event.inputs.environment }}-$(date +%Y%m%d%H%M%S)"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git checkout -b "$BRANCH_NAME"
git add .radius/plan/
git commit -m "Deployment plan for ${{ github.event.inputs.environment }}" --trailer "Radius-Action: plan"
git push --set-upstream origin "$BRANCH_NAME"
gh pr create --title "Deploy to ${{ github.event.inputs.environment }}" --body "This PR contains the deployment plan for environment **${{ github.event.inputs.environment }}**." --base main --head "$BRANCH_NAME"`,
		Env: map[string]string{
			"GH_TOKEN": "${{ github.token }}",
		},
	})

	return steps
}

// GenerateAuthTestWorkflow creates the OIDC authentication test workflow.
// FR-031-A: Creates .github/workflows/radius-auth-test.yaml
// FR-031-B: Triggered by push events modifying .radius/env.*.yaml files
func GenerateAuthTestWorkflow(provider string) *Workflow {
	workflow := &Workflow{
		Name:    "Radius Auth Test",
		RunName: "Radius authentication test",
		On: WorkflowTrigger{
			Push: &PushTrigger{
				Paths: []string{".radius/env.*.yaml"},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "read",
		},
		Jobs: map[string]WorkflowJob{},
	}

	// Add provider-specific auth test job
	if provider == "aws" {
		workflow.Jobs["test-aws-auth"] = WorkflowJob{
			Name:   "Test AWS OIDC Authentication",
			RunsOn: "ubuntu-latest",
			Steps:  generateAWSAuthTestSteps(),
		}
	} else if provider == "azure" {
		workflow.Jobs["test-azure-auth"] = WorkflowJob{
			Name:   "Test Azure OIDC Authentication",
			RunsOn: "ubuntu-latest",
			Steps:  generateAzureAuthTestSteps(),
		}
	}

	return workflow
}

// generateAWSAuthTestSteps creates steps for testing AWS OIDC authentication.
// FR-031-C: Verify OIDC auth by calling aws sts get-caller-identity
func generateAWSAuthTestSteps() []WorkflowStep {
	return []WorkflowStep{
		{
			Name: "Checkout",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"fetch-depth": "2", // Need history for git diff
			},
		},
		{
			Name: "Parse environment config",
			ID:   "env",
			Run: `# Find the environment file - try git diff first, then fallback to listing
ENV_FILE=""
if git rev-parse HEAD~1 >/dev/null 2>&1; then
  ENV_FILE=$(git diff --name-only HEAD~1 HEAD | grep -F '.radius/env.' | grep '\.yaml$' | head -1)
fi
if [ -z "$ENV_FILE" ]; then
  ENV_FILE=$(find .radius -name 'env.*.yaml' 2>/dev/null | head -1)
fi

if [ -z "$ENV_FILE" ]; then
  echo "Error: No environment file found in .radius/"
  exit 1
fi
echo "Using environment file: $ENV_FILE"

# Parse AWS configuration using yq
ROLE_ARN=$(yq -e '.provider.aws.oidcRoleARN // ""' "$ENV_FILE" 2>/dev/null || echo "")
REGION=$(yq -e '.provider.aws.region // ""' "$ENV_FILE" 2>/dev/null || echo "")
BUCKET=$(yq -e '.provider.aws.stateBackend.bucket // ""' "$ENV_FILE" 2>/dev/null || echo "")

# Debug output
echo "Parsed values from $ENV_FILE:"
echo "  role-arn: ${ROLE_ARN:0:20}***"
echo "  region: $REGION"

# Validate required fields
if [ -z "$ROLE_ARN" ] || [ "$ROLE_ARN" = "null" ]; then
  echo "Error: oidcRoleARN not found in environment file"
  exit 1
fi
if [ -z "$REGION" ] || [ "$REGION" = "null" ]; then
  echo "Error: region not found in environment file"
  exit 1
fi

echo "role-arn=$ROLE_ARN" >> $GITHUB_OUTPUT
echo "region=$REGION" >> $GITHUB_OUTPUT
echo "bucket=$BUCKET" >> $GITHUB_OUTPUT`,
		},
		{
			Name: "Configure AWS credentials via OIDC",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "${{ steps.env.outputs.role-arn }}",
				"aws-region":     "${{ steps.env.outputs.region }}",
			},
		},
		{
			Name: "Verify AWS authentication",
			Run: `echo "Testing AWS OIDC authentication..."
IDENTITY=$(aws sts get-caller-identity --output json)
echo "✅ AWS OIDC authentication successful!"
echo "Account: $(echo $IDENTITY | jq -r '.Account')"
echo "ARN: $(echo $IDENTITY | jq -r '.Arn')"`,
		},
		{
			Name: "Test S3 state backend access",
			If:   "steps.env.outputs.bucket != ''",
			Run: `echo "Testing Terraform state backend access..."
if aws s3 ls "s3://${{ steps.env.outputs.bucket }}" &>/dev/null; then
  echo "✅ S3 state bucket accessible"
else
  echo "⚠️ S3 state bucket not accessible (may not exist yet)"
fi`,
			ContinueOnError: true,
		},
	}
}

// Workflow file name constants for the two-phase deployment model.
const (
	// DeploymentCreateWorkflowFile is the filename for the deployment create workflow.
	DeploymentCreateWorkflowFile = "radius-deployment-create.yaml"

	// DeploymentApplyWorkflowFile is the filename for the deployment apply workflow.
	DeploymentApplyWorkflowFile = "radius-deployment-apply.yaml"

	// DestroyWorkflowFile is the filename for the destroy workflow.
	DestroyWorkflowFile = "radius-destroy.yaml"

	// AuthTestWorkflowFile is the filename for the auth test workflow.
	AuthTestWorkflowFile = "radius-auth-test.yaml"
)

// GenerateDeploymentCreateWorkflow creates the two-phase deployment create workflow.
// FR-098: Triggered via workflow_dispatch with application, environment, and commit inputs.
// FR-099: Uses concurrency groups scoped to application+environment.
// FR-112: Produces radius-deployment-create.yaml.
func GenerateDeploymentCreateWorkflow() *Workflow {
	workflow := &Workflow{
		HeaderComments: []string{
			"CUSTOMIZATION GUIDE:",
			"To trigger on push instead of workflow_dispatch, replace the 'on' section with:",
			"  on:",
			"    push:",
			"      branches: [main]",
			"      paths: ['.radius/applications/**']",
			"",
			"To trigger on pull_request:",
			"  on:",
			"    pull_request:",
			"      branches: [main]",
			"      types: [opened, synchronize]",
			"",
			"To add multi-environment promotion with approval gates:",
			"  Add 'needs: [create]' to a second job and set 'environment: staging'",
			"  GitHub Environment protection rules will enforce approvals.",
			"",
			"The deployment plan at .radius/deploy/<app>/<env>/<commit>/ contains:",
			"  deploy.yaml - Plan metadata and step definitions",
			"  <step>/artifacts/ - Terraform files (main.tf, providers.tf, etc.)",
			"  These can be used with 'terraform apply' directly for external tool execution.",
			"",
			"GitHub Secrets are available in steps via ${{ secrets.SECRET_NAME }}",
		},
		Name:    "Radius deployment create",
		RunName: "Radius deployment create for ${{ inputs.application }} in ${{ inputs.environment }} environment",
		On: WorkflowTrigger{
			WorkflowDispatch: &WorkflowDispatchTrigger{
				Inputs: map[string]WorkflowInput{
					"application": {
						Description: "Application name (must match a .bicep file in .radius/applications/)",
						Required:    true,
						Type:        "string",
					},
					"environment": {
						Description: "Target GitHub Environment name",
						Required:    true,
						Type:        "string",
					},
					"commit": {
						Description: "Git commit hash for this deployment plan",
						Required:    true,
						Type:        "string",
					},
				},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "write",
			"actions":  "read",
		},
		Concurrency: &WorkflowConcurrency{
			Group:            "radius-${{ inputs.application }}-${{ inputs.environment }}",
			CancelInProgress: false,
		},
		Jobs: map[string]WorkflowJob{
			"create": {
				Name:        "Generate Deployment Plan",
				RunsOn:      "ubuntu-latest",
				Environment: "${{ inputs.environment }}",
				Steps:       generateDeploymentCreateSteps(),
			},
		},
	}

	return workflow
}

// GenerateDeploymentApplyWorkflow creates the two-phase deployment apply workflow.
// FR-098: Triggered via workflow_dispatch with application, environment, and commit inputs.
// FR-099: Uses concurrency groups scoped to application+environment.
// FR-112: Produces radius-deployment-apply.yaml.
func GenerateDeploymentApplyWorkflow() *Workflow {
	workflow := &Workflow{
		HeaderComments: []string{
			"CUSTOMIZATION GUIDE:",
			"To trigger after deployment create completes (CI/CD pipeline):",
			"  on:",
			"    workflow_run:",
			"      workflows: ['Radius deployment create']",
			"      types: [completed]",
			"",
			"To trigger on merge to main (after PR review of the plan):",
			"  on:",
			"    push:",
			"      branches: [main]",
			"      paths: ['.radius/deploy/**']",
			"",
			"To require approval before applying, configure GitHub Environment",
			"protection rules with required reviewers.",
			"",
			"GitHub Secrets are available in steps via ${{ secrets.SECRET_NAME }}",
		},
		Name:    "Radius deployment apply",
		RunName: "Radius deployment apply for ${{ inputs.application }} in ${{ inputs.environment }} environment",
		On: WorkflowTrigger{
			WorkflowDispatch: &WorkflowDispatchTrigger{
				Inputs: map[string]WorkflowInput{
					"application": {
						Description: "Application name",
						Required:    true,
						Type:        "string",
					},
					"environment": {
						Description: "Target GitHub Environment name",
						Required:    true,
						Type:        "string",
					},
					"commit": {
						Description: "Git commit hash identifying the deployment plan to apply",
						Required:    true,
						Type:        "string",
					},
				},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "write",
			"actions":  "read",
		},
		Concurrency: &WorkflowConcurrency{
			Group:            "radius-${{ inputs.application }}-${{ inputs.environment }}",
			CancelInProgress: false,
		},
		Jobs: map[string]WorkflowJob{
			"apply": {
				Name:        "Apply Deployment Plan",
				RunsOn:      "ubuntu-latest",
				Environment: "${{ inputs.environment }}",
				Steps:       generateDeploymentApplySteps(),
			},
		},
	}

	return workflow
}

// GenerateDestroyWorkflowV2 creates the destroy workflow for the two-phase model.
// FR-112: Produces radius-destroy.yaml triggered by workflow_dispatch.
func GenerateDestroyWorkflowV2() *Workflow {
	workflow := &Workflow{
		HeaderComments: []string{
			"CUSTOMIZATION GUIDE:",
			"To add a scheduled cleanup (e.g., destroy dev environments nightly):",
			"  on:",
			"    schedule:",
			"      - cron: '0 2 * * *'",
			"",
			"GitHub Secrets are available in steps via ${{ secrets.SECRET_NAME }}",
		},
		Name:    "Radius destroy",
		RunName: "Radius destroy for ${{ inputs.application }} in ${{ inputs.environment }} environment",
		On: WorkflowTrigger{
			WorkflowDispatch: &WorkflowDispatchTrigger{
				Inputs: map[string]WorkflowInput{
					"application": {
						Description: "Application name to destroy",
						Required:    true,
						Type:        "string",
					},
					"environment": {
						Description: "Target GitHub Environment name",
						Required:    true,
						Type:        "string",
					},
				},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "write",
			"actions":  "read",
		},
		Concurrency: &WorkflowConcurrency{
			Group:            "radius-${{ inputs.application }}-${{ inputs.environment }}",
			CancelInProgress: false,
		},
		Jobs: map[string]WorkflowJob{
			"destroy": {
				Name:        "Destroy Application",
				RunsOn:      "ubuntu-latest",
				Environment: "${{ inputs.environment }}",
				Steps:       generateDestroyStepsV2(),
			},
		},
	}

	return workflow
}

// GenerateAuthTestWorkflowV2 creates the OIDC authentication test workflow for the two-phase model.
// FR-112: Produces radius-auth-test.yaml triggered by workflow_dispatch.
func GenerateAuthTestWorkflowV2() *Workflow {
	workflow := &Workflow{
		HeaderComments: []string{
			"CUSTOMIZATION GUIDE:",
			"This workflow tests OIDC authentication to your cloud provider.",
			"It is dispatched automatically by 'rad environment create' but can also be run manually.",
			"",
			"GitHub Secrets are available in steps via ${{ secrets.SECRET_NAME }}",
		},
		Name:    "Radius authentication test",
		RunName: "Radius authentication test for ${{ inputs.environment }} environment",
		On: WorkflowTrigger{
			WorkflowDispatch: &WorkflowDispatchTrigger{
				Inputs: map[string]WorkflowInput{
					"environment": {
						Description: "GitHub Environment to test authentication for",
						Required:    true,
						Type:        "string",
					},
				},
			},
		},
		Permissions: map[string]string{
			"id-token": "write",
			"contents": "read",
		},
		Jobs: map[string]WorkflowJob{
			"test-auth": {
				Name:        "Test OIDC Authentication",
				RunsOn:      "ubuntu-latest",
				Environment: "${{ inputs.environment }}",
				Steps:       generateAuthTestStepsV2(),
			},
		},
	}

	return workflow
}

func generateDeploymentCreateSteps() []WorkflowStep {
	return []WorkflowStep{
		// Step 1: Checkout the Radius source for building the CLI
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		// Step 2: Setup Go for building the CLI
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version-file": "radius-src/go.mod",
				"cache":           "true",
			},
		},
		// Step 3: Build the Radius CLI
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		// Step 4: Checkout the application repository at the specified commit
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"ref":  "${{ inputs.commit }}",
				"path": "app",
			},
		},
		// Step 5: Clone resource types repository
		// FR-092-B: Clone resource types repo for bicepconfig.json and Bicep extensions
		{
			Name: "Clone resource types repository",
			Env: map[string]string{
				"RADIUS_RESOURCE_TYPES_REPO": "${{ vars.RADIUS_RESOURCE_TYPES_REPO }}",
			},
			Run: `# Parse RADIUS_RESOURCE_TYPES_REPO URL (format: https://github.com/<owner>/<repo>/tree/<branch>)
REPO_PATH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|https://github.com/||' | sed 's|/tree/.*||')
BRANCH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|.*/tree/||')

git clone --depth 1 --branch "$BRANCH" "https://github.com/${REPO_PATH}.git" resource-types

# Copy bicepconfig.json and Bicep extension archives to app directory
# so rad deploy can resolve Bicep extensions (Bicep searches parent dirs from .bicep file)
cp resource-types/default-config/bicepconfig.json app/
cp resource-types/default-config/*.tgz app/`,
		},
		// Step 6: Install k3d for ephemeral cluster
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		// Step 7: Create ephemeral k3d cluster
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		// Step 8: Export kubeconfig
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		// Step 9: Install Radius control plane
		// FR-088-A: Skip contour install and disable dashboard
		{
			Name: "Install Radius control plane",
			Run:  "cd app && rad install kubernetes --skip-contour-install --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// Step 10: Wait for control plane readiness then create resource group.
		// D053: UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 11: Register resource types from types.yaml
		// FR-092-C: Read types.yaml and register each resource type in the control plane
		{
			Name: "Register resource types",
			Run: `cd resource-types/default-config
for def_file in $(yq -r '.types[].definitionLocation' types.yaml); do
  echo "Registering resource type from $def_file..."
  rad resource-type create --from-file "$def_file"
done`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 12: Create environment
		// Environment is created in the Radius control plane using the GitHub Environment name.
		// This bridges the GitHub Environment (which holds cloud credentials and config)
		// with a Radius environment (which the control plane needs for deployment).
		{
			Name: "Create environment",
			Run:  "rad env create ${{ inputs.environment }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 13: Cloud authentication (reads from GitHub Environment variables)
		// The workflow uses the GitHub Environment specified in the job,
		// so environment variables are automatically available.
		{
			Name: "Configure cloud credentials",
			ID:   "auth",
			Env: map[string]string{
				"AZURE_CLIENT_ID":   "${{ vars.AZURE_CLIENT_ID }}",
				"AWS_IAM_ROLE_NAME": "${{ vars.AWS_IAM_ROLE_NAME }}",
			},
			Run: `# Detect provider from environment variables
if [ -n "$AZURE_CLIENT_ID" ]; then
  echo "provider=azure" >> $GITHUB_OUTPUT
elif [ -n "$AWS_IAM_ROLE_NAME" ]; then
  echo "provider=aws" >> $GITHUB_OUTPUT
else
  echo "No cloud provider credentials found in environment"
  exit 1
fi`,
		},
		// Step 9a: Azure OIDC login (conditional)
		{
			Name: "Azure Login",
			If:   "steps.auth.outputs.provider == 'azure'",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ vars.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ vars.AZURE_TENANT_ID }}",
				"subscription-id": "${{ vars.AZURE_SUBSCRIPTION_ID }}",
			},
		},
		// Step 9b: AWS OIDC credentials (conditional)
		{
			Name: "Configure AWS credentials",
			If:   "steps.auth.outputs.provider == 'aws'",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE_NAME }}",
				"aws-region":     "${{ vars.AWS_REGION }}",
			},
		},
		// Step 10: Generate the deployment plan
		// This step runs rad deploy in plan-only mode to produce deploy.yaml and artifacts
		{
			Name: "Generate deployment plan",
			Run: `cd app
PLAN_DIR=".radius/deploy/${{ inputs.application }}/${{ inputs.environment }}/${{ inputs.commit }}"
mkdir -p "$PLAN_DIR"

# Generate deployment plan via Radius control plane
rad deploy ".radius/applications/${{ inputs.application }}.bicep" \
  --application "${{ inputs.application }}" \
  --environment "${{ inputs.environment }}" \
  --group github \
  --plan \
  --output "$PLAN_DIR"`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 11: Commit and push the deployment plan
		{
			Name: "Commit deployment plan",
			Run: `cd app
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add ".radius/deploy/${{ inputs.application }}/${{ inputs.environment }}/${{ inputs.commit }}/"
git commit -m "Deployment plan for ${{ inputs.application }} in ${{ inputs.environment }} at ${{ inputs.commit }}" \
  --trailer "Radius-Action: deployment-create"
git push origin HEAD:${{ github.ref_name }}`,
		},
	}
}

func generateDeploymentApplySteps() []WorkflowStep {
	return []WorkflowStep{
		// Step 1: Checkout the Radius source for building the CLI
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		// Step 2: Setup Go for building the CLI
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version-file": "radius-src/go.mod",
				"cache":           "true",
			},
		},
		// Step 3: Build the Radius CLI
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		// Step 4: Checkout the application repository (latest, so it has the plan)
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"path": "app",
			},
		},
		// Step 5: Clone resource types repository
		// FR-092-B: Clone resource types repo for bicepconfig.json and Bicep extensions
		{
			Name: "Clone resource types repository",
			Env: map[string]string{
				"RADIUS_RESOURCE_TYPES_REPO": "${{ vars.RADIUS_RESOURCE_TYPES_REPO }}",
			},
			Run: `# Parse RADIUS_RESOURCE_TYPES_REPO URL (format: https://github.com/<owner>/<repo>/tree/<branch>)
REPO_PATH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|https://github.com/||' | sed 's|/tree/.*||')
BRANCH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|.*/tree/||')

git clone --depth 1 --branch "$BRANCH" "https://github.com/${REPO_PATH}.git" resource-types

# Copy bicepconfig.json and Bicep extension archives to app directory
# so rad deploy can resolve Bicep extensions (Bicep searches parent dirs from .bicep file)
cp resource-types/default-config/bicepconfig.json app/
cp resource-types/default-config/*.tgz app/`,
		},
		// Step 6: Install k3d for ephemeral cluster
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		// Step 7: Create ephemeral k3d cluster
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		// Step 8: Export kubeconfig
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		// Step 9: Install Radius control plane
		// FR-088-A: Skip contour install and disable dashboard
		{
			Name: "Install Radius control plane",
			Run:  "cd app && rad install kubernetes --skip-contour-install --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// Step 10: Wait for control plane readiness then create resource group.
		// D053: UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 11: Register resource types from types.yaml
		// FR-092-C: Read types.yaml and register each resource type in the control plane
		{
			Name: "Register resource types",
			Run: `cd resource-types/default-config
for def_file in $(yq -r '.types[].definitionLocation' types.yaml); do
  echo "Registering resource type from $def_file..."
  rad resource-type create --from-file "$def_file"
done`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 12: Create environment
		// Environment is created in the Radius control plane using the GitHub Environment name.
		// This bridges the GitHub Environment (which holds cloud credentials and config)
		// with a Radius environment (which the control plane needs for deployment).
		{
			Name: "Create environment",
			Run:  "rad env create ${{ inputs.environment }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 13: Cloud authentication
		{
			Name: "Configure cloud credentials",
			ID:   "auth",
			Env: map[string]string{
				"AZURE_CLIENT_ID":   "${{ vars.AZURE_CLIENT_ID }}",
				"AWS_IAM_ROLE_NAME": "${{ vars.AWS_IAM_ROLE_NAME }}",
			},
			Run: `# Detect provider from environment variables
if [ -n "$AZURE_CLIENT_ID" ]; then
  echo "provider=azure" >> $GITHUB_OUTPUT
elif [ -n "$AWS_IAM_ROLE_NAME" ]; then
  echo "provider=aws" >> $GITHUB_OUTPUT
else
  echo "No cloud provider credentials found in environment"
  exit 1
fi`,
		},
		{
			Name: "Azure Login",
			If:   "steps.auth.outputs.provider == 'azure'",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ vars.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ vars.AZURE_TENANT_ID }}",
				"subscription-id": "${{ vars.AZURE_SUBSCRIPTION_ID }}",
			},
		},
		{
			Name: "Configure AWS credentials",
			If:   "steps.auth.outputs.provider == 'aws'",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE_NAME }}",
				"aws-region":     "${{ vars.AWS_REGION }}",
			},
		},
		// Step 10: Apply the deployment plan
		{
			Name: "Apply deployment plan",
			Run: `cd app
PLAN_DIR=".radius/deploy/${{ inputs.application }}/${{ inputs.environment }}/${{ inputs.commit }}"

if [ ! -d "$PLAN_DIR" ]; then
  echo "Error: No deployment plan found at $PLAN_DIR"
  echo "Run 'rad deployment create' first to generate a plan."
  exit 1
fi

# Apply deployment using the existing plan
rad deploy ".radius/applications/${{ inputs.application }}.bicep" \
  --application "${{ inputs.application }}" \
  --environment "${{ inputs.environment }}" \
  --group github \
  --apply "$PLAN_DIR"`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Step 11: Update deployment record and commit
		{
			Name: "Record deployment results",
			If:   "always()",
			Run: `cd app
PLAN_DIR=".radius/deploy/${{ inputs.application }}/${{ inputs.environment }}/${{ inputs.commit }}"

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add "$PLAN_DIR/"
git commit -m "Deployment results for ${{ inputs.application }} in ${{ inputs.environment }} at ${{ inputs.commit }}" \
  --trailer "Radius-Action: deployment-apply" || true
git push origin HEAD:${{ github.ref_name }}`,
		},
	}
}

func generateDestroyStepsV2() []WorkflowStep {
	return []WorkflowStep{
		{
			Name: "Checkout Radius source",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"repository": "${{ vars.RADIUS_REPO || 'radius-project/radius' }}",
				"ref":        "${{ vars.RADIUS_REF || 'main' }}",
				"path":       "radius-src",
			},
		},
		{
			Name: "Setup Go",
			Uses: "actions/setup-go@v5",
			With: map[string]string{
				"go-version-file": "radius-src/go.mod",
				"cache":           "true",
			},
		},
		{
			Name: "Build Radius CLI",
			Run:  "cd radius-src && go build -o /usr/local/bin/rad ./cmd/rad",
		},
		{
			Name: "Checkout application repository",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"path": "app",
			},
		},
		// Clone resource types repository
		// FR-092-B: Clone resource types repo for bicepconfig.json and Bicep extensions
		{
			Name: "Clone resource types repository",
			Env: map[string]string{
				"RADIUS_RESOURCE_TYPES_REPO": "${{ vars.RADIUS_RESOURCE_TYPES_REPO }}",
			},
			Run: `# Parse RADIUS_RESOURCE_TYPES_REPO URL (format: https://github.com/<owner>/<repo>/tree/<branch>)
REPO_PATH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|https://github.com/||' | sed 's|/tree/.*||')
BRANCH=$(echo "$RADIUS_RESOURCE_TYPES_REPO" | sed 's|.*/tree/||')

git clone --depth 1 --branch "$BRANCH" "https://github.com/${REPO_PATH}.git" resource-types

# Copy bicepconfig.json and Bicep extension archives to app directory
# so rad deploy can resolve Bicep extensions (Bicep searches parent dirs from .bicep file)
cp resource-types/default-config/bicepconfig.json app/
cp resource-types/default-config/*.tgz app/`,
		},
		{
			Name: "Install k3d",
			Run:  "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash",
		},
		{
			Name: "Create k3d cluster",
			Run:  "k3d cluster create radius-ephemeral --volume $GITHUB_WORKSPACE/app:/github_workspace",
		},
		{
			Name: "Export kubeconfig",
			Run:  "k3d kubeconfig get radius-ephemeral > /tmp/kubeconfig.yaml",
		},
		{
			Name: "Install Radius control plane",
			Run:  "cd app && rad install kubernetes --skip-contour-install --set dashboard.enabled=false ${RADIUS_IMAGE_REGISTRY:+--set global.imageRegistry=$RADIUS_IMAGE_REGISTRY} ${RADIUS_IMAGE_TAG:+--set global.imageTag=$RADIUS_IMAGE_TAG}",
			Env: map[string]string{
				"KUBECONFIG":            "/tmp/kubeconfig.yaml",
				"RADIUS_IMAGE_REGISTRY": "${{ vars.RADIUS_IMAGE_REGISTRY }}",
				"RADIUS_IMAGE_TAG":      "${{ vars.RADIUS_IMAGE_TAG }}",
			},
		},
		// D053: Wait for control plane readiness then create resource group.
		// UCP registers built-in providers asynchronously after pod start;
		// rad group create will fail until that completes.
		{
			Name: "Wait for Radius and create resource group",
			Run: `echo "Waiting for Radius control plane to be ready..."
for i in $(seq 1 30); do
  if rad group create github 2>/dev/null; then
    echo "Radius control plane is ready, resource group created."
    exit 0
  fi
  echo "Control plane not ready yet, retrying in 5s... ($i/30)"
  sleep 5
done
echo "Timed out waiting for Radius control plane"
exit 1`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Register resource types from types.yaml
		// FR-092-C: Read types.yaml and register each resource type in the control plane
		{
			Name: "Register resource types",
			Run: `cd resource-types/default-config
for def_file in $(yq -r '.types[].definitionLocation' types.yaml); do
  echo "Registering resource type from $def_file..."
  rad resource-type create --from-file "$def_file"
done`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Create environment
		// Environment is created in the Radius control plane using the GitHub Environment name.
		// This bridges the GitHub Environment (which holds cloud credentials and config)
		// with a Radius environment (which the control plane needs for deployment).
		{
			Name: "Create environment",
			Run:  "rad env create ${{ inputs.environment }} --group github",
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		{
			Name: "Configure cloud credentials",
			ID:   "auth",
			Env: map[string]string{
				"AZURE_CLIENT_ID":   "${{ vars.AZURE_CLIENT_ID }}",
				"AWS_IAM_ROLE_NAME": "${{ vars.AWS_IAM_ROLE_NAME }}",
			},
			Run: `# Detect provider from environment variables
if [ -n "$AZURE_CLIENT_ID" ]; then
  echo "provider=azure" >> $GITHUB_OUTPUT
elif [ -n "$AWS_IAM_ROLE_NAME" ]; then
  echo "provider=aws" >> $GITHUB_OUTPUT
else
  echo "No cloud provider credentials found in environment"
  exit 1
fi`,
		},
		{
			Name: "Azure Login",
			If:   "steps.auth.outputs.provider == 'azure'",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ vars.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ vars.AZURE_TENANT_ID }}",
				"subscription-id": "${{ vars.AZURE_SUBSCRIPTION_ID }}",
			},
		},
		{
			Name: "Configure AWS credentials",
			If:   "steps.auth.outputs.provider == 'aws'",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE_NAME }}",
				"aws-region":     "${{ vars.AWS_REGION }}",
			},
		},
		// Destroy the application
		{
			Name: "Destroy application",
			Run: `cd app
rad app delete "${{ inputs.application }}" \
  --environment "${{ inputs.environment }}" \
  --group github \
  --yes`,
			Env: map[string]string{
				"KUBECONFIG": "/tmp/kubeconfig.yaml",
			},
		},
		// Update deployment records to reflect destroy
		{
			Name: "Record destruction results",
			If:   "always()",
			Run: `cd app
DEPLOY_DIR=".radius/deploy/${{ inputs.application }}/${{ inputs.environment }}"

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add "$DEPLOY_DIR/" 2>/dev/null || true
git commit -m "Destroy ${{ inputs.application }} from ${{ inputs.environment }}" \
  --trailer "Radius-Action: destroy" || true
git push origin HEAD:${{ github.ref_name }}`,
		},
	}
}

func generateAuthTestStepsV2() []WorkflowStep {
	return []WorkflowStep{
		{
			Name: "Checkout",
			Uses: "actions/checkout@v4",
		},
		// Detect provider from environment variables
		{
			Name: "Detect provider",
			ID:   "provider",
			Env: map[string]string{
				"AZURE_CLIENT_ID":   "${{ vars.AZURE_CLIENT_ID }}",
				"AWS_IAM_ROLE_NAME": "${{ vars.AWS_IAM_ROLE_NAME }}",
			},
			Run: `if [ -n "$AZURE_CLIENT_ID" ]; then
  echo "type=azure" >> $GITHUB_OUTPUT
elif [ -n "$AWS_IAM_ROLE_NAME" ]; then
  echo "type=aws" >> $GITHUB_OUTPUT
else
  echo "Error: No cloud provider credentials found in ${{ inputs.environment }} environment variables"
  echo "Expected AZURE_CLIENT_ID (Azure) or AWS_IAM_ROLE_NAME (AWS)"
  exit 1
fi`,
		},
		// Azure OIDC test
		{
			Name: "Azure Login",
			If:   "steps.provider.outputs.type == 'azure'",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ vars.AZURE_CLIENT_ID }}",
				"tenant-id":       "${{ vars.AZURE_TENANT_ID }}",
				"subscription-id": "${{ vars.AZURE_SUBSCRIPTION_ID }}",
			},
		},
		{
			Name: "Verify Azure authentication",
			If:   "steps.provider.outputs.type == 'azure'",
			Run: `echo "Testing Azure OIDC authentication..."
ACCOUNT=$(az account show --output json)
echo "✅ Azure OIDC authentication successful!"
echo "Subscription: $(echo $ACCOUNT | jq -r '.name')"
echo "Tenant: $(echo $ACCOUNT | jq -r '.tenantId')"`,
		},
		// AWS OIDC test
		{
			Name: "Configure AWS credentials",
			If:   "steps.provider.outputs.type == 'aws'",
			Uses: "aws-actions/configure-aws-credentials@v4",
			With: map[string]string{
				"role-to-assume": "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE_NAME }}",
				"aws-region":     "${{ vars.AWS_REGION }}",
			},
		},
		{
			Name: "Verify AWS authentication",
			If:   "steps.provider.outputs.type == 'aws'",
			Run: `echo "Testing AWS OIDC authentication..."
IDENTITY=$(aws sts get-caller-identity --output json)
echo "✅ AWS OIDC authentication successful!"
echo "Account: $(echo $IDENTITY | jq -r '.Account')"
echo "ARN: $(echo $IDENTITY | jq -r '.Arn')"`,
		},
	}
}

// generateAzureAuthTestSteps creates steps for testing Azure OIDC authentication.
// FR-031-D: Verify OIDC auth by calling az account show
func generateAzureAuthTestSteps() []WorkflowStep {
	return []WorkflowStep{
		{
			Name: "Checkout",
			Uses: "actions/checkout@v4",
			With: map[string]string{
				"fetch-depth": "2", // Need history for git diff
			},
		},
		{
			Name: "Parse environment config",
			ID:   "env",
			Run: `# Find the environment file - try git diff first, then fallback to listing
ENV_FILE=""
if git rev-parse HEAD~1 >/dev/null 2>&1; then
  ENV_FILE=$(git diff --name-only HEAD~1 HEAD | grep -F '.radius/env.' | grep '\.yaml$' | head -1)
fi
if [ -z "$ENV_FILE" ]; then
  ENV_FILE=$(find .radius -name 'env.*.yaml' 2>/dev/null | head -1)
fi

if [ -z "$ENV_FILE" ]; then
  echo "Error: No environment file found in .radius/"
  exit 1
fi
echo "Using environment file: $ENV_FILE"

# Parse Azure configuration using yq
CLIENT_ID=$(yq -e '.provider.azure.clientId // ""' "$ENV_FILE" 2>/dev/null || echo "")
TENANT_ID=$(yq -e '.provider.azure.tenantId // ""' "$ENV_FILE" 2>/dev/null || echo "")
SUBSCRIPTION_ID=$(yq -e '.provider.azure.subscriptionId // ""' "$ENV_FILE" 2>/dev/null || echo "")
STORAGE_ACCOUNT=$(yq -e '.provider.azure.stateBackend.storageAccountName // ""' "$ENV_FILE" 2>/dev/null || echo "")

# Debug output
echo "Parsed values from $ENV_FILE:"
echo "  client-id: ${CLIENT_ID:0:8}***"
echo "  tenant-id: ${TENANT_ID:0:8}***"
echo "  subscription-id: ${SUBSCRIPTION_ID:0:8}***"

# Validate required fields
if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" = "null" ]; then
  echo "Error: clientId not found in environment file"
  exit 1
fi
if [ -z "$TENANT_ID" ] || [ "$TENANT_ID" = "null" ]; then
  echo "Error: tenantId not found in environment file"
  exit 1
fi
if [ -z "$SUBSCRIPTION_ID" ] || [ "$SUBSCRIPTION_ID" = "null" ]; then
  echo "Error: subscriptionId not found in environment file"
  exit 1
fi

echo "client-id=$CLIENT_ID" >> $GITHUB_OUTPUT
echo "tenant-id=$TENANT_ID" >> $GITHUB_OUTPUT
echo "subscription-id=$SUBSCRIPTION_ID" >> $GITHUB_OUTPUT
echo "storage-account=$STORAGE_ACCOUNT" >> $GITHUB_OUTPUT`,
		},
		{
			Name: "Configure Azure credentials via OIDC",
			Uses: "azure/login@v2",
			With: map[string]string{
				"client-id":       "${{ steps.env.outputs.client-id }}",
				"tenant-id":       "${{ steps.env.outputs.tenant-id }}",
				"subscription-id": "${{ steps.env.outputs.subscription-id }}",
			},
		},
		{
			Name: "Verify Azure authentication",
			Run: `echo "Testing Azure OIDC authentication..."
ACCOUNT=$(az account show --output json)
echo "✅ Azure OIDC authentication successful!"
echo "Subscription: $(echo $ACCOUNT | jq -r '.name')"
echo "Tenant: $(echo $ACCOUNT | jq -r '.tenantId')"`,
		},
		{
			Name: "Test Storage state backend access",
			If:   "steps.env.outputs.storage-account != ''",
			Run: `echo "Testing Terraform state backend access..."
if az storage account show --name "${{ steps.env.outputs.storage-account }}" &>/dev/null; then
  echo "✅ Azure Storage account accessible"
else
  echo "⚠️ Azure Storage account not accessible (may not exist yet)"
fi`,
			ContinueOnError: true,
		},
	}
}
